---
- name: copy storm-rpm
  copy: src=x86_64/apache-storm-0.9.4-1.x86_64.rpm dest=/opt

- name: install storm
  yum: name=/opt/apache-storm-0.9.4-1.x86_64.rpm state=present

- name: create data directory
  file: path=/opt/apache-storm-0.9.4/data state=directory mode="u=rwx,g=rx,o=rx"

- name: change user
  command: chown -R root:root /opt

#- name: add hostname
#  lineinfile: dest=/etc/hosts
#              line="{{ hostvars[item]['ipv6_addr'] }} {{item}}"
#  with_items: groups['storm_hosts']

- include: nimbus.yml
# when: storm_nimbus_enabled

- include: supervisor.yml

- template: >
    src=storm.yaml.j2
    dest=/opt/apache-storm-0.9.4/conf/storm.yaml
    mode=666
    owner=root
 # notify: Restart storm

- name: change user 
  command: chown -R root:root /opt

- name: Setup Nimbus service
  copy: dest="/etc/supervisord.d" src=nimbus.ini
  notify: restart supervisord

- name: Setup supervisor service
  copy: dest="/etc/supervisord.d" src=supervisor.ini
  notify: restart supervisord

- name: Setup Ui service
  copy: dest="/etc/supervisord.d" src=ui.ini
  notify: restart supervisord
