---
- name: create baching shell
  template: src=con.j2 dest=/etc/tinc/myvpn/hosts/trans.sh

- name: create hostname file
  template: src=host.j2 dest=/etc/tinc/myvpn/hosts/hostname

- name: change to hosts folder
  command: cd /etc/tinc/myvpn/hosts

- name: change the authority of batching shell
  file: path=/etc/tinc/myvpn/hosts/trans.sh mode=777

- name: trans the pubkey
  command: /etc/tinc/myvpn/hosts/trans.sh
