---
- include: stop.yml
  when: run_mode == 'Stop'

- include: install.yml
  when: run_mode == 'Install'

- include: mstart.yml
  when: run_mode == 'MStart'

- include: sstart.yml
  when: run_mode == 'SStart'
