---
- name: Install the mariadb-server
  yum: name=mariadb-server state=present

- name: Install the dependency packages MySQL-python
  yum: name=MySQL-python state=present

- name: Setup Mysql service
  copy: dest="/etc/supervisord.d" src=mysql.ini
  notify: restart supervisord
