---
- name: ssh password less configure
  hosts: all
  sudo: yes
  roles:
    - pub_ssh

- name: install common components
  hosts: all
  remote_user: root
  sudo: yes
  roles:
    - { role: pub_common, ansible_user_pass: 'root', ansible_sudo_pass: 'root' }

- name: install zookeeper
  hosts: zookeeper
  remote_user: root
  sudo: yes
  roles:
    - { role: pub_zookeeper, run_mode: 'Install' }

- name: install kafka
  hosts: kafka
  remote_user: root
  sudo: yes
  roles:
    - { role: pub_kafka, run_mode: 'Install' }

- name: install redis
  hosts: redis
  remote_user: root
  sudo: yes
  roles:
    - { role: pub_redis, run_mode: 'Install' }

- name: install tinc route
  hosts: tinc_route
  remote_user: root
  sudo: yes
  roles:
    - { role: pub_tinc, run_mode: 'Install_r' }

- name: install tinc
  hosts: tinc_node
  remote_user: root
  sudo: yes
  roles:
    - { role: pub_tinc, run_mode: 'Install_n' }

- name: exchange pub_key
  hosts: tinc_route,tinc_node
  remote_user: root
  sudo: yes
  roles:
    - { role: pub_tinc, run_mode: 'Connect' }

- name: install storm
  hosts: storm
  remote_user: root
  sudo: yes
  roles:
    - { role: pub_storm, run_mode: 'Install' }

- name: install hadoop
  hosts: hadoop
  remote_user: root
  sudo: yes
  roles:
    - { role: pub_hadoop, run_mode: 'Install' }

- name: install MySQL
  hosts: mysql
  remote_user: root
  sudo: yes
  roles:
    - { role: pub_mysql, run_mode: 'Install' }
    
- name: install eThtest
  hosts: eThtest
  remote_user: root
  sudo: yes
  roles:
    - { role: pub_datacollect, run_mode: 'Install' }

- name: install Data Part
  hosts: data_server
  remote_user: root
  sudo: yes
  roles:
    - { role: data, run_mode: 'Install' }
    
- name: install Monitor Part
  hosts: monitor_server
  remote_user: root
  sudo: yes
  roles:
    - { role: monitor, run_mode: 'Install' }
    
- name: install NetWork Part
  hosts: network_server
  remote_user: root
  sudo: yes
  roles:
    - {role: network, run_mode: 'Install' }
